#!/usr/bin/env bash
# E2E and Visual Regression Gate (Gate 7)
# Runs Playwright E2E tests with visual regression using toHaveScreenshot()

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Source dev server utilities
source "$SCRIPT_DIR/lib/dev-server-utils.sh"

# Color output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

log_info() { echo -e "${BLUE}[E2E]${NC} $*"; }
log_success() { echo -e "${GREEN}[E2E]${NC} $*"; }
log_warning() { echo -e "${YELLOW}[E2E]${NC} $*"; }
log_error() { echo -e "${RED}[E2E]${NC} $*"; }

# Configuration (can be overridden by user-preferences.yaml)
E2E_ENABLED="${E2E_ENABLED:-true}"
E2E_FAILURE_MODE="${E2E_FAILURE_MODE:-blocking}"
E2E_THRESHOLD="${E2E_THRESHOLD:-0.1}"
E2E_AUTO_COMMIT_BASELINES="${E2E_AUTO_COMMIT_BASELINES:-true}"

# Load user preferences if available
load_preferences() {
    local prefs_file=".spec-flow/config/user-preferences.yaml"

    if [ -f "$prefs_file" ]; then
        # Extract e2e_visual settings using grep (YAML-safe)
        local enabled=$(grep -A 10 "^e2e_visual:" "$prefs_file" 2>/dev/null | grep "enabled:" | head -1 | awk '{print $2}')
        local failure_mode=$(grep -A 10 "^e2e_visual:" "$prefs_file" 2>/dev/null | grep "failure_mode:" | head -1 | awk '{print $2}')
        local threshold=$(grep -A 10 "^e2e_visual:" "$prefs_file" 2>/dev/null | grep "threshold:" | head -1 | awk '{print $2}')
        local auto_commit=$(grep -A 10 "^e2e_visual:" "$prefs_file" 2>/dev/null | grep "auto_commit_baselines:" | head -1 | awk '{print $2}')

        [ -n "$enabled" ] && E2E_ENABLED="$enabled"
        [ -n "$failure_mode" ] && E2E_FAILURE_MODE="$failure_mode"
        [ -n "$threshold" ] && E2E_THRESHOLD="$threshold"
        [ -n "$auto_commit" ] && E2E_AUTO_COMMIT_BASELINES="$auto_commit"
    fi
}

# Check if Playwright is configured
has_playwright_config() {
    [ -f "playwright.config.ts" ] || [ -f "playwright.config.js" ] || [ -f "playwright.config.mjs" ]
}

# Check if Playwright is installed
is_playwright_installed() {
    npx playwright --version >/dev/null 2>&1
}

# Detect baselines directory for this feature/epic
get_baselines_dir() {
    local feature_dir="$1"
    echo "${feature_dir}/e2e/baselines"
}

# Check if baselines exist (first-run detection)
has_baselines() {
    local baselines_dir="$1"
    [ -d "$baselines_dir" ] && [ -n "$(ls -A "$baselines_dir" 2>/dev/null)" ]
}

# Auto-commit generated baselines
commit_baselines() {
    local feature_dir="$1"
    local slug="$2"
    local baselines_dir="${feature_dir}/e2e/baselines"

    if [ "$E2E_AUTO_COMMIT_BASELINES" != "true" ]; then
        log_info "Auto-commit disabled, skipping baseline commit"
        return 0
    fi

    if [ ! -d "$baselines_dir" ] || [ -z "$(ls -A "$baselines_dir" 2>/dev/null)" ]; then
        log_warning "No baselines to commit"
        return 0
    fi

    log_info "Auto-committing generated baselines..."

    git add "${baselines_dir}/" 2>/dev/null || true

    if git diff --cached --quiet 2>/dev/null; then
        log_info "No new baselines to commit"
        return 0
    fi

    git commit -m "chore(e2e): add visual baselines for ${slug}

Generated by /optimize Gate 7 (E2E + Visual)

$(echo "${baselines_dir}/" | head -1)" 2>/dev/null || {
        log_warning "Failed to commit baselines (may already be committed)"
        return 0
    }

    log_success "Baselines committed"
}

# Main gate function
run_e2e_visual_gate() {
    local feature_dir="${1:-.}"
    local slug="${2:-unknown}"

    local result_file="${feature_dir}/optimization-e2e.md"
    : > "$result_file"

    echo "# E2E and Visual Regression Results" >> "$result_file"
    echo "" >> "$result_file"
    echo "**Feature**: ${slug}" >> "$result_file"
    echo "**Date**: $(date -u +%Y-%m-%dT%H:%M:%SZ)" >> "$result_file"
    echo "" >> "$result_file"

    # Load user preferences
    load_preferences

    # Check if E2E is enabled
    if [ "$E2E_ENABLED" != "true" ]; then
        echo "Status: SKIPPED" >> "$result_file"
        echo "Reason: E2E testing disabled in user-preferences.yaml" >> "$result_file"
        log_info "E2E tests skipped (disabled in preferences)"
        return 0
    fi

    # Check for Playwright config
    if ! has_playwright_config; then
        echo "Status: SKIPPED" >> "$result_file"
        echo "Reason: No playwright.config.ts/js found" >> "$result_file"
        echo "" >> "$result_file"
        echo "To enable E2E testing:" >> "$result_file"
        echo "  1. Install: npm init playwright@latest" >> "$result_file"
        echo "  2. Configure: playwright.config.ts" >> "$result_file"
        echo "  3. Create tests in e2e/ or tests/" >> "$result_file"
        echo "  4. Re-run /optimize" >> "$result_file"
        log_info "E2E tests skipped (no Playwright config found)"
        return 0
    fi

    # Check if Playwright is installed
    if ! is_playwright_installed; then
        echo "Status: SKIPPED" >> "$result_file"
        echo "Reason: Playwright not installed" >> "$result_file"
        echo "" >> "$result_file"
        echo "Run: npx playwright install" >> "$result_file"
        log_warning "E2E tests skipped (run 'npx playwright install')"
        return 0
    fi

    # Setup cleanup trap
    setup_dev_server_cleanup_trap

    # Start dev server if needed
    log_info "Checking dev server..."
    if ! start_dev_server; then
        echo "Status: FAILED" >> "$result_file"
        echo "Reason: Dev server failed to start" >> "$result_file"
        echo "" >> "$result_file"
        echo "Check logs: tail -f /tmp/dev-server-3000.log" >> "$result_file"
        log_error "E2E tests failed: Dev server not responding"
        return 1
    fi

    log_success "Dev server ready"

    # Check for baselines (first-run detection)
    local baselines_dir
    baselines_dir=$(get_baselines_dir "$feature_dir")
    local first_run=false

    if ! has_baselines "$baselines_dir"; then
        first_run=true
        log_warning "First run detected - baselines will be generated"
        echo "## First Run Detected" >> "$result_file"
        echo "" >> "$result_file"
        echo "No visual baselines found. Generating initial baselines..." >> "$result_file"
        echo "" >> "$result_file"

        # Create baselines directory
        mkdir -p "$baselines_dir"
    fi

    # Run Playwright tests
    log_info "Running Playwright E2E tests..."
    local test_log="${feature_dir}/e2e-test-results.log"
    local test_exit_code=0

    if [ "$first_run" = true ]; then
        # First run: generate baselines with --update-snapshots
        npx playwright test --update-snapshots --reporter=list 2>&1 | tee "$test_log" || test_exit_code=$?
    else
        # Subsequent runs: compare against baselines
        npx playwright test --reporter=list 2>&1 | tee "$test_log" || test_exit_code=$?
    fi

    # Analyze results
    echo "## Test Results" >> "$result_file"
    echo "" >> "$result_file"

    if [ "$test_exit_code" -eq 0 ]; then
        echo "Status: PASSED" >> "$result_file"

        if [ "$first_run" = true ]; then
            echo "Note: First run - baselines generated (not compared)" >> "$result_file"
            log_success "E2E tests passed (baselines generated)"

            # Auto-commit baselines
            commit_baselines "$feature_dir" "$slug"

            # Return warning status for first run
            echo "" >> "$result_file"
            echo "## Warning" >> "$result_file"
            echo "" >> "$result_file"
            echo "This was the first run. Visual baselines have been generated but not validated." >> "$result_file"
            echo "Run /optimize again to perform actual visual comparison." >> "$result_file"

            # Cleanup dev server
            cleanup_dev_server

            # First run is a WARNING, not a PASS
            return 0
        else
            log_success "E2E tests passed"
        fi
    else
        echo "Status: FAILED" >> "$result_file"
        echo "" >> "$result_file"
        echo "### Failure Details" >> "$result_file"
        echo "" >> "$result_file"
        echo '```' >> "$result_file"
        tail -50 "$test_log" >> "$result_file"
        echo '```' >> "$result_file"
        log_error "E2E tests failed (exit code: $test_exit_code)"

        # Cleanup dev server
        cleanup_dev_server

        # Check failure mode
        if [ "$E2E_FAILURE_MODE" = "warning" ]; then
            log_warning "E2E failure mode is 'warning', continuing..."
            return 0
        else
            return 1
        fi
    fi

    # Cleanup dev server
    cleanup_dev_server

    return 0
}

# Entry point
main() {
    local feature_dir="${1:-.}"
    local slug="${2:-unknown}"

    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo "Gate 7: E2E and Visual Regression"
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo ""

    run_e2e_visual_gate "$feature_dir" "$slug"
}

# Run if executed directly
if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    main "$@"
fi
