#!/usr/bin/env bash
# Interaction State Manager v1.0
# Handle question/answer flow for isolated phase agents
#
# Usage:
#   interaction-manager.sh init <feature-dir>
#   interaction-manager.sh save-questions <dir> <phase> <questions-json>
#   interaction-manager.sh save-answers <dir> <answers-json>
#   interaction-manager.sh get-pending <dir>
#   interaction-manager.sh get-answers <dir> <phase>
#   interaction-manager.sh clear-pending <dir>
#   interaction-manager.sh mark-phase-complete <dir> <phase>
#   interaction-manager.sh get-phase-status <dir> <phase>
#   interaction-manager.sh status <dir>

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
TEMPLATE_DIR="$(dirname "$SCRIPT_DIR")/../templates"

# Color output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Check for yq
check_yq() {
    if ! command -v yq &> /dev/null; then
        echo -e "${RED}Error: yq is required but not installed${NC}" >&2
        echo "Install with: brew install yq (macOS) or apt install yq (Linux)" >&2
        exit 1
    fi
}

# Initialize interaction state for a feature/epic directory
cmd_init() {
    local dir="$1"

    if [ -z "$dir" ]; then
        echo -e "${RED}Error: Directory required${NC}" >&2
        echo "Usage: interaction-manager.sh init <feature-dir>" >&2
        exit 1
    fi

    if [ ! -d "$dir" ]; then
        echo -e "${RED}Error: Directory does not exist: $dir${NC}" >&2
        exit 1
    fi

    local state_file="$dir/interaction-state.yaml"

    if [ -f "$state_file" ]; then
        echo -e "${YELLOW}Warning: interaction-state.yaml already exists at $state_file${NC}"
        echo "Use 'interaction-manager.sh status $dir' to view current state"
        exit 0
    fi

    # Determine workflow type from path
    local workflow_type="feature"
    if [[ "$dir" == *"epics/"* ]]; then
        workflow_type="epic"
    fi

    # Extract slug from directory
    local slug=$(basename "$dir")

    # Copy template and customize
    local timestamp=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

    cat > "$state_file" << EOF
# Interaction State v1.0
# Auto-generated by interaction-manager.sh

version: "1.0"
created: "$timestamp"
last_updated: "$timestamp"

current_phase: null

pending:
  phase: null
  session_id: null
  questions: []
  resume_instructions:
    agent: null
    entry_point: null
    context_to_pass: {}

sessions: []

phases_completed:
  spec: false
  clarify: false
  plan: false
  tasks: false
  implement: false
  optimize: false
  validate: false
  ship: false
  finalize: false

artifacts:
  spec: { created: [], modified: [], summary: null }
  clarify: { created: [], modified: [], summary: null }
  plan: { created: [], modified: [], summary: null }
  tasks: { created: [], modified: [], summary: null }
  implement: { created: [], modified: [], summary: null }
  optimize: { created: [], modified: [], summary: null }
  validate: { created: [], modified: [], summary: null }
  ship: { created: [], modified: [], summary: null }
  finalize: { created: [], modified: [], summary: null }

workflow:
  type: "$workflow_type"
  slug: "$slug"
  started_at: "$timestamp"
  total_questions_asked: 0
  total_sessions: 0
EOF

    echo -e "${GREEN}Initialized interaction state at $state_file${NC}"
}

# Save questions from a phase agent
cmd_save_questions() {
    local dir="$1"
    local phase="$2"
    local questions_json="$3"

    if [ -z "$dir" ] || [ -z "$phase" ] || [ -z "$questions_json" ]; then
        echo -e "${RED}Error: Missing arguments${NC}" >&2
        echo "Usage: interaction-manager.sh save-questions <dir> <phase> <questions-json>" >&2
        exit 1
    fi

    local state_file="$dir/interaction-state.yaml"
    if [ ! -f "$state_file" ]; then
        echo -e "${YELLOW}Initializing interaction state...${NC}"
        cmd_init "$dir"
    fi

    local timestamp=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
    local session_id="$timestamp"

    # Update pending section
    yq eval -i ".pending.phase = \"$phase\"" "$state_file"
    yq eval -i ".pending.session_id = \"$session_id\"" "$state_file"
    yq eval -i ".pending.questions = $questions_json" "$state_file"
    yq eval -i ".pending.resume_instructions.agent = \"${phase}-agent\"" "$state_file"
    yq eval -i ".current_phase = \"$phase\"" "$state_file"
    yq eval -i ".last_updated = \"$timestamp\"" "$state_file"

    # Add to sessions as pending
    local session_count=$(yq eval '.sessions | length' "$state_file")
    yq eval -i ".sessions[$session_count].session_id = \"$session_id\"" "$state_file"
    yq eval -i ".sessions[$session_count].phase = \"$phase\"" "$state_file"
    yq eval -i ".sessions[$session_count].round = 1" "$state_file"
    yq eval -i ".sessions[$session_count].started_at = \"$timestamp\"" "$state_file"
    yq eval -i ".sessions[$session_count].status = \"pending\"" "$state_file"
    yq eval -i ".sessions[$session_count].questions_asked = $questions_json" "$state_file"

    # Increment counters
    local total=$(yq eval '.workflow.total_sessions' "$state_file")
    yq eval -i ".workflow.total_sessions = $((total + 1))" "$state_file"

    local q_count=$(echo "$questions_json" | yq eval 'length' -)
    local total_q=$(yq eval '.workflow.total_questions_asked' "$state_file")
    yq eval -i ".workflow.total_questions_asked = $((total_q + q_count))" "$state_file"

    echo -e "${GREEN}Saved $q_count question(s) for phase '$phase'${NC}"
    echo "Session ID: $session_id"
}

# Save user answers
cmd_save_answers() {
    local dir="$1"
    local answers_json="$2"

    if [ -z "$dir" ] || [ -z "$answers_json" ]; then
        echo -e "${RED}Error: Missing arguments${NC}" >&2
        echo "Usage: interaction-manager.sh save-answers <dir> <answers-json>" >&2
        exit 1
    fi

    local state_file="$dir/interaction-state.yaml"
    if [ ! -f "$state_file" ]; then
        echo -e "${RED}Error: No interaction state found at $dir${NC}" >&2
        exit 1
    fi

    local timestamp=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
    local session_id=$(yq eval '.pending.session_id' "$state_file")

    if [ "$session_id" == "null" ]; then
        echo -e "${RED}Error: No pending session to answer${NC}" >&2
        exit 1
    fi

    # Find the pending session and update it
    local session_index=$(yq eval ".sessions | to_entries | map(select(.value.session_id == \"$session_id\")) | .[0].key" "$state_file")

    if [ "$session_index" != "null" ] && [ -n "$session_index" ]; then
        yq eval -i ".sessions[$session_index].completed_at = \"$timestamp\"" "$state_file"
        yq eval -i ".sessions[$session_index].status = \"completed\"" "$state_file"

        # Merge answers into questions_asked
        local questions=$(yq eval ".sessions[$session_index].questions_asked" "$state_file")
        # Parse answers_json and update each question
        echo "$answers_json" | yq eval 'to_entries | .[]' - | while read -r entry; do
            local q_id=$(echo "$entry" | yq eval '.key' -)
            local answer=$(echo "$entry" | yq eval '.value' -)
            local q_index=$(yq eval ".sessions[$session_index].questions_asked | to_entries | map(select(.value.id == \"$q_id\")) | .[0].key" "$state_file")
            if [ "$q_index" != "null" ] && [ -n "$q_index" ]; then
                yq eval -i ".sessions[$session_index].questions_asked[$q_index].answer = \"$answer\"" "$state_file"
                yq eval -i ".sessions[$session_index].questions_asked[$q_index].answered_at = \"$timestamp\"" "$state_file"
                yq eval -i ".sessions[$session_index].questions_asked[$q_index].answer_source = \"user_selection\"" "$state_file"
            fi
        done 2>/dev/null || true
    fi

    yq eval -i ".last_updated = \"$timestamp\"" "$state_file"

    echo -e "${GREEN}Saved answers for session $session_id${NC}"
}

# Get pending questions (returns JSON)
cmd_get_pending() {
    local dir="$1"

    if [ -z "$dir" ]; then
        echo -e "${RED}Error: Directory required${NC}" >&2
        exit 1
    fi

    local state_file="$dir/interaction-state.yaml"
    if [ ! -f "$state_file" ]; then
        echo '{"has_pending": false}'
        exit 0
    fi

    local phase=$(yq eval '.pending.phase' "$state_file")

    if [ "$phase" == "null" ]; then
        echo '{"has_pending": false}'
    else
        local questions=$(yq eval '.pending.questions' "$state_file" -o json)
        local resume=$(yq eval '.pending.resume_instructions' "$state_file" -o json)
        echo "{\"has_pending\": true, \"phase\": \"$phase\", \"questions\": $questions, \"resume\": $resume}"
    fi
}

# Get answers for a specific phase
cmd_get_answers() {
    local dir="$1"
    local phase="$2"

    if [ -z "$dir" ] || [ -z "$phase" ]; then
        echo -e "${RED}Error: Missing arguments${NC}" >&2
        exit 1
    fi

    local state_file="$dir/interaction-state.yaml"
    if [ ! -f "$state_file" ]; then
        echo '{"answers": {}}'
        exit 0
    fi

    # Get all completed sessions for this phase and extract answers
    yq eval ".sessions | map(select(.phase == \"$phase\" and .status == \"completed\")) | .[].questions_asked | map({(.id): .answer}) | add // {}" "$state_file" -o json
}

# Clear pending state after agent completion
cmd_clear_pending() {
    local dir="$1"

    if [ -z "$dir" ]; then
        echo -e "${RED}Error: Directory required${NC}" >&2
        exit 1
    fi

    local state_file="$dir/interaction-state.yaml"
    if [ ! -f "$state_file" ]; then
        exit 0
    fi

    local timestamp=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

    yq eval -i '.pending.phase = null' "$state_file"
    yq eval -i '.pending.session_id = null' "$state_file"
    yq eval -i '.pending.questions = []' "$state_file"
    yq eval -i '.pending.resume_instructions.agent = null' "$state_file"
    yq eval -i '.pending.resume_instructions.entry_point = null' "$state_file"
    yq eval -i '.pending.resume_instructions.context_to_pass = {}' "$state_file"
    yq eval -i ".last_updated = \"$timestamp\"" "$state_file"

    echo -e "${GREEN}Cleared pending state${NC}"
}

# Mark a phase as complete
cmd_mark_phase_complete() {
    local dir="$1"
    local phase="$2"

    if [ -z "$dir" ] || [ -z "$phase" ]; then
        echo -e "${RED}Error: Missing arguments${NC}" >&2
        exit 1
    fi

    local state_file="$dir/interaction-state.yaml"
    if [ ! -f "$state_file" ]; then
        echo -e "${RED}Error: No interaction state found${NC}" >&2
        exit 1
    fi

    local timestamp=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

    yq eval -i ".phases_completed.$phase = true" "$state_file"
    yq eval -i ".last_updated = \"$timestamp\"" "$state_file"

    # Clear pending if it was for this phase
    local pending_phase=$(yq eval '.pending.phase' "$state_file")
    if [ "$pending_phase" == "$phase" ]; then
        cmd_clear_pending "$dir"
    fi

    echo -e "${GREEN}Phase '$phase' marked as complete${NC}"
}

# Get phase completion status
cmd_get_phase_status() {
    local dir="$1"
    local phase="$2"

    if [ -z "$dir" ] || [ -z "$phase" ]; then
        echo -e "${RED}Error: Missing arguments${NC}" >&2
        exit 1
    fi

    local state_file="$dir/interaction-state.yaml"
    if [ ! -f "$state_file" ]; then
        echo "not_started"
        exit 0
    fi

    local completed=$(yq eval ".phases_completed.$phase" "$state_file")
    local pending=$(yq eval '.pending.phase' "$state_file")

    if [ "$completed" == "true" ]; then
        echo "completed"
    elif [ "$pending" == "$phase" ]; then
        echo "pending_input"
    else
        echo "not_started"
    fi
}

# Show overall status
cmd_status() {
    local dir="$1"

    if [ -z "$dir" ]; then
        echo -e "${RED}Error: Directory required${NC}" >&2
        exit 1
    fi

    local state_file="$dir/interaction-state.yaml"
    if [ ! -f "$state_file" ]; then
        echo -e "${YELLOW}No interaction state found at $dir${NC}"
        exit 0
    fi

    echo ""
    echo -e "${BLUE}═══════════════════════════════════════════════════════════════${NC}"
    echo -e "${BLUE}  Interaction State: $(basename $dir)${NC}"
    echo -e "${BLUE}═══════════════════════════════════════════════════════════════${NC}"
    echo ""

    # Workflow info
    local workflow_type=$(yq eval '.workflow.type' "$state_file")
    local started=$(yq eval '.workflow.started_at' "$state_file")
    local total_q=$(yq eval '.workflow.total_questions_asked' "$state_file")
    local total_s=$(yq eval '.workflow.total_sessions' "$state_file")

    echo -e "  Workflow: ${GREEN}$workflow_type${NC}"
    echo -e "  Started: $started"
    echo -e "  Total Questions: $total_q"
    echo -e "  Total Sessions: $total_s"
    echo ""

    # Phase status
    echo -e "  ${BLUE}Phase Status:${NC}"
    for phase in spec clarify plan tasks implement optimize validate ship finalize; do
        local status=$(cmd_get_phase_status "$dir" "$phase")
        local icon="○"
        local color="$NC"
        case "$status" in
            completed) icon="✓"; color="$GREEN" ;;
            pending_input) icon="?"; color="$YELLOW" ;;
        esac
        printf "    %s %-12s %b%s%b\n" "$icon" "$phase" "$color" "$status" "$NC"
    done
    echo ""

    # Pending questions
    local pending_phase=$(yq eval '.pending.phase' "$state_file")
    if [ "$pending_phase" != "null" ]; then
        echo -e "  ${YELLOW}Pending Questions (Phase: $pending_phase):${NC}"
        yq eval '.pending.questions[] | "    - " + .question' "$state_file" 2>/dev/null || true
        echo ""
    fi

    echo -e "${BLUE}═══════════════════════════════════════════════════════════════${NC}"
    echo ""
}

# Record artifacts from a phase
cmd_record_artifacts() {
    local dir="$1"
    local phase="$2"
    local artifacts_json="$3"

    if [ -z "$dir" ] || [ -z "$phase" ] || [ -z "$artifacts_json" ]; then
        echo -e "${RED}Error: Missing arguments${NC}" >&2
        exit 1
    fi

    local state_file="$dir/interaction-state.yaml"
    if [ ! -f "$state_file" ]; then
        echo -e "${RED}Error: No interaction state found${NC}" >&2
        exit 1
    fi

    local timestamp=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

    # Parse and record artifacts
    local created=$(echo "$artifacts_json" | yq eval '.created // []' - -o json)
    local modified=$(echo "$artifacts_json" | yq eval '.modified // []' - -o json)
    local summary=$(echo "$artifacts_json" | yq eval '.summary // ""' -)

    yq eval -i ".artifacts.$phase.created = $created" "$state_file"
    yq eval -i ".artifacts.$phase.modified = $modified" "$state_file"
    yq eval -i ".artifacts.$phase.summary = \"$summary\"" "$state_file"
    yq eval -i ".last_updated = \"$timestamp\"" "$state_file"

    echo -e "${GREEN}Recorded artifacts for phase '$phase'${NC}"
}

# Main command router
main() {
    check_yq

    local command="${1:-help}"
    shift || true

    case "$command" in
        init)
            cmd_init "$@"
            ;;
        save-questions)
            cmd_save_questions "$@"
            ;;
        save-answers)
            cmd_save_answers "$@"
            ;;
        get-pending)
            cmd_get_pending "$@"
            ;;
        get-answers)
            cmd_get_answers "$@"
            ;;
        clear-pending)
            cmd_clear_pending "$@"
            ;;
        mark-phase-complete)
            cmd_mark_phase_complete "$@"
            ;;
        get-phase-status)
            cmd_get_phase_status "$@"
            ;;
        record-artifacts)
            cmd_record_artifacts "$@"
            ;;
        status)
            cmd_status "$@"
            ;;
        help|--help|-h)
            echo "Interaction State Manager v1.0"
            echo ""
            echo "Commands:"
            echo "  init <dir>                           Initialize interaction state"
            echo "  save-questions <dir> <phase> <json>  Save pending questions from agent"
            echo "  save-answers <dir> <json>            Save user answers"
            echo "  get-pending <dir>                    Get pending questions (JSON)"
            echo "  get-answers <dir> <phase>            Get answers for phase (JSON)"
            echo "  clear-pending <dir>                  Clear pending state"
            echo "  mark-phase-complete <dir> <phase>    Mark phase as complete"
            echo "  get-phase-status <dir> <phase>       Get phase status"
            echo "  record-artifacts <dir> <phase> <json> Record phase artifacts"
            echo "  status <dir>                         Show overall status"
            echo ""
            ;;
        *)
            echo -e "${RED}Unknown command: $command${NC}" >&2
            echo "Run 'interaction-manager.sh help' for usage" >&2
            exit 1
            ;;
    esac
}

main "$@"
