import { test, expect, Page } from '@playwright/test';

/**
 * Visual Regression Test Template for Spec-Flow
 *
 * This template demonstrates:
 * - Visual snapshot testing with toHaveScreenshot()
 * - Animation disabling for consistent screenshots
 * - Dynamic content masking
 * - Multiple viewport testing
 *
 * Usage:
 * 1. Copy this file to your e2e/tests/ directory
 * 2. Customize the routes and selectors for your app
 * 3. Run: npx playwright test
 * 4. First run generates baselines in e2e/baselines/
 * 5. Subsequent runs compare against baselines
 *
 * Generated by Spec-Flow /optimize workflow
 */

/**
 * Disable all animations and transitions for consistent screenshots
 * Call this before taking any screenshot
 */
async function disableAnimations(page: Page): Promise<void> {
  await page.evaluate(() => {
    const style = document.createElement('style');
    style.id = 'playwright-disable-animations';
    style.textContent = `
      *, *::before, *::after {
        animation-duration: 0s !important;
        animation-delay: 0s !important;
        transition-duration: 0s !important;
        transition-delay: 0s !important;
        scroll-behavior: auto !important;
      }
    `;
    document.head.appendChild(style);
  });

  // Wait for any in-flight animations to complete
  await page.waitForTimeout(100);
}

/**
 * Wait for all images and fonts to load
 */
async function waitForAssetsLoaded(page: Page): Promise<void> {
  await page.waitForLoadState('networkidle');

  // Wait for images
  await page.evaluate(async () => {
    const images = Array.from(document.images);
    await Promise.all(
      images
        .filter((img) => !img.complete)
        .map(
          (img) =>
            new Promise((resolve) => {
              img.onload = resolve;
              img.onerror = resolve;
            })
        )
    );
  });

  // Wait for fonts
  await page.evaluate(() => document.fonts.ready);
}

// ============================================================
// Homepage Visual Tests
// ============================================================

test.describe('Homepage Visual Tests', () => {
  test.beforeEach(async ({ page }) => {
    await page.goto('/');
    await waitForAssetsLoaded(page);
    await disableAnimations(page);
  });

  test('homepage matches visual baseline @visual', async ({ page }) => {
    await expect(page).toHaveScreenshot('homepage.png', {
      fullPage: true,
      // Mask dynamic content that changes between runs
      mask: [
        // Uncomment and customize selectors for your app:
        // page.locator('.timestamp'),
        // page.locator('.user-avatar'),
        // page.locator('[data-testid="random-content"]'),
      ],
    });
  });

  test('homepage header matches baseline @visual', async ({ page }) => {
    const header = page.locator('header');
    await expect(header).toHaveScreenshot('homepage-header.png');
  });

  test('homepage footer matches baseline @visual', async ({ page }) => {
    const footer = page.locator('footer');
    // Scroll footer into view first
    await footer.scrollIntoViewIfNeeded();
    await expect(footer).toHaveScreenshot('homepage-footer.png');
  });
});

// ============================================================
// Responsive Visual Tests
// ============================================================

test.describe('Responsive Visual Tests', () => {
  const viewports = [
    { name: 'desktop', width: 1280, height: 720 },
    { name: 'tablet', width: 768, height: 1024 },
    { name: 'mobile', width: 375, height: 667 },
  ];

  for (const viewport of viewports) {
    test(`homepage at ${viewport.name} viewport @visual @responsive`, async ({
      page,
    }) => {
      await page.setViewportSize({
        width: viewport.width,
        height: viewport.height,
      });
      await page.goto('/');
      await waitForAssetsLoaded(page);
      await disableAnimations(page);

      await expect(page).toHaveScreenshot(`homepage-${viewport.name}.png`, {
        fullPage: true,
      });
    });
  }
});

// ============================================================
// Component State Visual Tests
// ============================================================

test.describe('Component State Visual Tests', () => {
  test('button states @visual @states', async ({ page }) => {
    await page.goto('/');
    await disableAnimations(page);

    const button = page.locator('button').first();

    // Default state
    await expect(button).toHaveScreenshot('button-default.png');

    // Hover state
    await button.hover();
    await expect(button).toHaveScreenshot('button-hover.png');

    // Focus state
    await button.focus();
    await expect(button).toHaveScreenshot('button-focus.png');
  });
});

// ============================================================
// Dark Mode Visual Tests (if applicable)
// ============================================================

test.describe('Dark Mode Visual Tests', () => {
  test('homepage in dark mode @visual @dark-mode', async ({ page }) => {
    // Enable dark mode via media query emulation
    await page.emulateMedia({ colorScheme: 'dark' });
    await page.goto('/');
    await waitForAssetsLoaded(page);
    await disableAnimations(page);

    await expect(page).toHaveScreenshot('homepage-dark.png', {
      fullPage: true,
    });
  });

  test('homepage in light mode @visual @light-mode', async ({ page }) => {
    await page.emulateMedia({ colorScheme: 'light' });
    await page.goto('/');
    await waitForAssetsLoaded(page);
    await disableAnimations(page);

    await expect(page).toHaveScreenshot('homepage-light.png', {
      fullPage: true,
    });
  });
});

// ============================================================
// Critical User Flow Visual Tests
// ============================================================

test.describe('Critical User Flow Visual Tests', () => {
  test('login flow visual regression @visual @flow', async ({ page }) => {
    // Navigate to login
    await page.goto('/login');
    await waitForAssetsLoaded(page);
    await disableAnimations(page);

    // Screenshot: Login form empty state
    await expect(page).toHaveScreenshot('login-empty.png');

    // Fill form
    await page.fill('[name="email"]', 'test@example.com');
    await page.fill('[name="password"]', 'password123');

    // Screenshot: Login form filled state
    await expect(page).toHaveScreenshot('login-filled.png');

    // Note: Don't actually submit in visual tests to avoid side effects
    // For E2E behavior tests, create separate non-visual tests
  });
});

// ============================================================
// Error State Visual Tests
// ============================================================

test.describe('Error State Visual Tests', () => {
  test('404 page matches baseline @visual @error', async ({ page }) => {
    await page.goto('/this-page-does-not-exist');
    await waitForAssetsLoaded(page);
    await disableAnimations(page);

    await expect(page).toHaveScreenshot('404-page.png', {
      fullPage: true,
    });
  });
});
