import { defineConfig, devices } from '@playwright/test';

/**
 * Playwright Configuration for Spec-Flow E2E + Visual Testing
 *
 * This template provides:
 * - Deterministic visual snapshots (animations disabled, consistent fonts)
 * - Per-feature/epic baseline storage
 * - Desktop and mobile viewport presets
 * - Headless mode in CI environments
 *
 * Generated by Spec-Flow /optimize workflow
 */
export default defineConfig({
  // Test directory - adjust based on your project structure
  testDir: './e2e/tests',

  // Run tests in parallel
  fullyParallel: true,

  // Fail the build on CI if you accidentally left test.only in the source code
  forbidOnly: !!process.env.CI,

  // Retry failed tests (helps with flaky visual tests)
  retries: process.env.CI ? 2 : 0,

  // Opt out of parallel tests on CI for more consistent results
  workers: process.env.CI ? 1 : undefined,

  // Reporter configuration
  reporter: [
    ['list'],
    ['html', { outputFolder: './e2e-results/playwright-report' }],
  ],

  // Test output directory (gitignored)
  outputDir: './e2e-results/test-results',

  // Global timeout for each test
  timeout: 30000,

  // Expect timeout for assertions
  expect: {
    timeout: 5000,

    // Visual comparison settings
    toHaveScreenshot: {
      // Maximum allowed pixel difference ratio (0.1 = 10%)
      maxDiffPixelRatio: 0.1,

      // Animation handling - disable for consistent snapshots
      animations: 'disabled',

      // Caret blinking disabled for consistency
      caret: 'hide',
    },

    toMatchSnapshot: {
      // Threshold for image comparison
      maxDiffPixelRatio: 0.1,
    },
  },

  // Shared settings for all projects
  use: {
    // Base URL for navigation
    baseURL: process.env.BASE_URL || 'http://localhost:3000',

    // Collect trace on first retry for debugging
    trace: 'on-first-retry',

    // Screenshot on failure for debugging
    screenshot: 'only-on-failure',

    // Video recording (disabled by default to save resources)
    video: 'off',

    // Headless mode in CI
    headless: !!process.env.CI,

    // Consistent browser rendering
    launchOptions: {
      args: [
        '--font-render-hinting=none', // Consistent font rendering
        '--disable-lcd-text', // Prevent subpixel rendering differences
      ],
    },
  },

  // Snapshot path configuration - per-feature/epic storage
  snapshotPathTemplate: '{testDir}/../baselines/{testFilePath}/{arg}{ext}',

  // Browser projects
  projects: [
    {
      name: 'Desktop Chrome',
      use: {
        ...devices['Desktop Chrome'],
        viewport: { width: 1280, height: 720 },
      },
    },
    {
      name: 'Mobile Safari',
      use: {
        ...devices['iPhone 13'],
        viewport: { width: 375, height: 667 },
      },
    },
  ],

  // Web server configuration (optional - use if you want Playwright to start the server)
  // Uncomment if not using external dev server management
  // webServer: {
  //   command: 'npm run dev',
  //   url: 'http://localhost:3000',
  //   reuseExistingServer: !process.env.CI,
  //   timeout: 60000,
  // },
});
